# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/authorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Authorization(object):
    def setupUi(self, Admittance):
        Admittance.setObjectName("Admittance")
        Admittance.resize(427, 332)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/../icons/main_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Admittance.setWindowIcon(icon)
        Admittance.setStyleSheet("background-color:     #333333")
        self.start_login_button = QtWidgets.QPushButton(Admittance)
        self.start_login_button.setGeometry(QtCore.QRect(120, 110, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Display Bold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.start_login_button.setFont(font)
        self.start_login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_login_button.setStyleSheet("color: white;\n"
"background-color: #0080ff;\n"
"border-radius: 12;\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/../icons/authorization/login_3.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.start_login_button.setIcon(icon1)
        self.start_login_button.setIconSize(QtCore.QSize(25, 25))
        self.start_login_button.setObjectName("start_login_button")
        self.start_regisration_button = QtWidgets.QPushButton(Admittance)
        self.start_regisration_button.setGeometry(QtCore.QRect(90, 220, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Display Bold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.start_regisration_button.setFont(font)
        self.start_regisration_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_regisration_button.setStyleSheet("color: white;\n"
"background-color: #0080ff;\n"
"border-radius: 12;\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui/../icons/authorization/registrated.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.start_regisration_button.setIcon(icon2)
        self.start_regisration_button.setIconSize(QtCore.QSize(25, 25))
        self.start_regisration_button.setObjectName("start_regisration_button")
        self.label_13 = QtWidgets.QLabel(Admittance)
        self.label_13.setGeometry(QtCore.QRect(100, 20, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Text Bold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: white;\n"
"background-color: #333333")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Admittance)
        self.label_14.setGeometry(QtCore.QRect(200, 180, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Text Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: white;\n"
"background-color: #333333")
        self.label_14.setObjectName("label_14")

        self.retranslateUi(Admittance)
        QtCore.QMetaObject.connectSlotsByName(Admittance)

    def retranslateUi(self, Admittance):
        _translate = QtCore.QCoreApplication.translate
        Admittance.setWindowTitle(_translate("Admittance", "Dialog"))
        self.start_login_button.setText(_translate("Admittance", "Login"))
        self.start_regisration_button.setText(_translate("Admittance", "Rregistration"))
        self.label_13.setText(_translate("Admittance", "What you nead ?"))
        self.label_14.setText(_translate("Admittance", "or"))
