# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/choose_defoult_templateui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChooseDefault(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(389, 428)
        font = QtGui.QFont()
        font.setPointSize(8)
        Dialog.setFont(font)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("background-color:     #333333")
        self.scrollArea_6 = QtWidgets.QScrollArea(Dialog)
        self.scrollArea_6.setGeometry(QtCore.QRect(50, 110, 291, 241))
        self.scrollArea_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_6.setLineWidth(0)
        self.scrollArea_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 291, 241))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_10 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_10.sizePolicy().hasHeightForWidth())
        self.radioButton_10.setSizePolicy(sizePolicy)
        self.radioButton_10.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Display Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_10.setFont(font)
        self.radioButton_10.setStyleSheet("background-color: #0080ff;\n"
"border-radius: 10;\n"
"color: white\n"
"")
        self.radioButton_10.setAutoRepeatDelay(1)
        self.radioButton_10.setAutoRepeatInterval(1)
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout.addWidget(self.radioButton_10)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, -30, 391, 121))
        self.frame.setStyleSheet("background-color: #0080ff;\n"
"border-radius: 13;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(10, 60, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Text Bold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: white;\n"
"background-color: #0080ff;")
        self.label_13.setObjectName("label_13")
        self.finish_chiise_button = QtWidgets.QPushButton(Dialog)
        self.finish_chiise_button.setGeometry(QtCore.QRect(120, 370, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Display Bold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.finish_chiise_button.setFont(font)
        self.finish_chiise_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.finish_chiise_button.setStyleSheet("color: white;\n"
"background-color: #0080ff;\n"
"border-radius: 12;\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/../icons/main_window/templte/set_template.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.finish_chiise_button.setIcon(icon)
        self.finish_chiise_button.setIconSize(QtCore.QSize(40, 40))
        self.finish_chiise_button.setObjectName("finish_chiise_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radioButton_10.setText(_translate("Dialog", "Defoult2"))
        self.label_13.setText(_translate("Dialog", "Choose defoult template"))
        self.finish_chiise_button.setText(_translate("Dialog", "Set"))
