# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/error.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Error(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(414, 314)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/../icons/main_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color:     #333333")
        self.er_button = QtWidgets.QPushButton(Dialog)
        self.er_button.setGeometry(QtCore.QRect(170, 230, 71, 71))
        self.er_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.er_button.setStyleSheet("color: white;\n"
"border-radius: 30;")
        self.er_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/../icons/message/retry.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.er_button.setIcon(icon1)
        self.er_button.setIconSize(QtCore.QSize(80, 80))
        self.er_button.setObjectName("er_button")
        self.label_error = QtWidgets.QLabel(Dialog)
        self.label_error.setGeometry(QtCore.QRect(120, 10, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Text Bold")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_error.setFont(font)
        self.label_error.setStyleSheet("color: white")
        self.label_error.setObjectName("label_error")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(140, 200, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Display Light")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.message_label = QtWidgets.QLabel(Dialog)
        self.message_label.setGeometry(QtCore.QRect(60, 80, 301, 91))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Display Light")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.message_label.setFont(font)
        self.message_label.setStyleSheet("color: white")
        self.message_label.setAlignment(QtCore.Qt.AlignCenter)
        self.message_label.setWordWrap(True)
        self.message_label.setObjectName("message_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_error.setText(_translate("Dialog", "Error!"))
        self.label_3.setText(_translate("Dialog", "You can retry"))
        self.message_label.setText(_translate("Dialog", "You have problem."))
