# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/frame_for_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(199, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setMinimumSize(QtCore.QSize(190, 300))
        Frame.setStyleSheet("border-radius: 15;\n"
"background-color: rgba(0,127,255, 70);")
        self.title = QtWidgets.QLabel(Frame)
        self.title.setGeometry(QtCore.QRect(20, 10, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Text Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("color: white;\n"
"background-color: rgb(255,160,0, 0);\n"
"")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.time = QtWidgets.QLabel(Frame)
        self.time.setGeometry(QtCore.QRect(30, 120, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Text Bold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.time.setFont(font)
        self.time.setStyleSheet("color: white;\n"
"background-color: rgb(255,160,0, 0);\n"
"")
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.music = QtWidgets.QLabel(Frame)
        self.music.setGeometry(QtCore.QRect(20, 190, 161, 81))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Display")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.music.setFont(font)
        self.music.setStyleSheet("color: white;\n"
"background-color: rgb(255,160,0, 0);\n"
"")
        self.music.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.music.setWordWrap(True)
        self.music.setObjectName("music")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.title.setText(_translate("Frame", "Урок - 1"))
        self.time.setText(_translate("Frame", "08:29"))
        self.music.setText(_translate("Frame", "Уведомление"))
