# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/logining.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(481, 338)
        Dialog.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/../icons/main_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setStyleSheet("background-color:     #333333")
        self.password_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.password_lineEdit.setGeometry(QtCore.QRect(100, 185, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Display")
        font.setPointSize(12)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.password_lineEdit.setStyleSheet("border-radius: 9; \n"
"border: 2px solid white;\n"
"color: white")
        self.password_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.login_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.login_lineEdit.setGeometry(QtCore.QRect(100, 60, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Display")
        font.setPointSize(12)
        self.login_lineEdit.setFont(font)
        self.login_lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.login_lineEdit.setStyleSheet("border-radius: 9; \n"
"border: 2px solid white;\n"
"color: white")
        self.login_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.login_lineEdit.setObjectName("login_lineEdit")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(180, 20, 111, 37))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("ui/../icons/loginig/login_2.png"))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Text Bold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(160, 140, 171, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("ui/../icons/loginig/password_2.png"))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Text Bold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.go_sistem_button_log = QtWidgets.QPushButton(Dialog)
        self.go_sistem_button_log.setGeometry(QtCore.QRect(170, 245, 146, 66))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Display Bold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.go_sistem_button_log.setFont(font)
        self.go_sistem_button_log.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.go_sistem_button_log.setStyleSheet("color: white;\n"
"background-color: #0080ff;\n"
"border-radius: 15;\n"
"")
        self.go_sistem_button_log.setObjectName("go_sistem_button_log")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "loginig"))
        self.label.setText(_translate("Dialog", "Login"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.go_sistem_button_log.setText(_translate("Dialog", "GO"))
