# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/set_schedul_on_day.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetSchedule(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(462, 179)
        Dialog.setStyleSheet("background-color:     #333333")
        self.time_tamble_combobox = QtWidgets.QComboBox(Dialog)
        self.time_tamble_combobox.setGeometry(QtCore.QRect(220, 40, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Display Regular")
        font.setPointSize(18)
        self.time_tamble_combobox.setFont(font)
        self.time_tamble_combobox.setStyleSheet("border-radius : 10; \n"
"border : 0px solid white;\n"
"background-color: #0080ff;\n"
"color: white")
        self.time_tamble_combobox.setEditable(False)
        self.time_tamble_combobox.setObjectName("time_tamble_combobox")
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(10, 40, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Display Regular")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit.setFont(font)
        self.dateEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateEdit.setStyleSheet("border-radius : 10; \n"
"border : 0px solid white;\n"
"background-color: #0080ff;\n"
"color: white")
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setObjectName("dateEdit")
        self.add_schedule_button = QtWidgets.QPushButton(Dialog)
        self.add_schedule_button.setGeometry(QtCore.QRect(150, 110, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Display Bold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.add_schedule_button.setFont(font)
        self.add_schedule_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_schedule_button.setStyleSheet("color: white;\n"
"background-color: #0080ff;\n"
"border-radius: 12;\n"
"")
        self.add_schedule_button.setIconSize(QtCore.QSize(25, 25))
        self.add_schedule_button.setObjectName("add_schedule_button")
        self.label_66 = QtWidgets.QLabel(Dialog)
        self.label_66.setGeometry(QtCore.QRect(10, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Display Thin")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_66.setFont(font)
        self.label_66.setStyleSheet("color: white;\n"
"background-color: rgb(255,160,0, 0);\n"
"")
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setWordWrap(True)
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(Dialog)
        self.label_67.setGeometry(QtCore.QRect(230, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Yandex Sans Display Thin")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("color: white;\n"
"background-color: rgb(255,160,0, 0);\n"
"")
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setWordWrap(True)
        self.label_67.setObjectName("label_67")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.add_schedule_button.setText(_translate("Dialog", "Add"))
        self.label_66.setText(_translate("Dialog", "Date"))
        self.label_67.setText(_translate("Dialog", "Template"))
